######################################################################
# Automatically generated by qmake (3.0) Mon Aug 22 19:06:33 2016
######################################################################

TEMPLATE = app
TARGET = browser
INCLUDEPATH += .

# Input
HEADERS += browser.h
FORMS += browser.ui
SOURCES += browser.cpp main.cpp
